### ISSUE TITLE
Does this library support forward kinematics code generation?

### ISSUE THREAD

**Issue by phuicy** [cdsousa/SymPyBotics#14]
Does this library support forward kinematics code generation?

**Comment by costashatz** [comment]
hey.. I am no sure that there exists code generation to use as is, but I am using this script:

```python
from sympybotics.symcode import Subexprs, code_to_func
from sympybotics.dynamics.rne import rne_forward

dof = #number of joints
for i in range(dof):
    g_se = Subexprs()
    fw_code = g_se.get(rbt.geo.T[i])

    T_str = sympybotics.robotcodegen.robot_code_to_func('python', fw_code, 'T_out', 'T_'+str(i), rbtdef)
```

**Comment by cdsousa** [comment]
Thanks @costashatz , I was just about to answer that it is possible by that way.

**Comment by phuicy** [comment]
Brilliant thanks. I had just hacked something similar to this:
```python
    g_se = Subexprs()
    fw_code = g_se.get(rbt.geo.T[i])
```
but i had not worked out the individual joints.

I might be forced to generate documentation for this project :)

thanks,
Guy

**Comment by phuicy** [comment]
As a note this only gives you xyz not roll pitch and yaw.

**Comment by ShawnSong1993** [comment]
I want to know how to translate the regress matrixs into minmum prameter regress matrix

**Comment by jnh277** [comment]
Hi, just wondering if it is also possible to compute the forward dynamics someway. i.e. calculate ddq given tau dq q and the params?
