### ISSUE TITLE
Dynamic Parameters 

### ISSUE THREAD

**Issue by Theesh76** [cdsousa/SymPyBotics#15]
In the test examples, the dynamic parameters values (dynparm_test) were used to generate Centrifugal, inertial, gravity matrices. The dynamic parameters values (dynparm_test) were given as a row vector as a input. I would like to know in which way the row vector had to be constructed ( for eg (m_1 r_x r_y r_z ....) or (r_x r_y r_z m_1.....)). I tried to figure it out by comparing the values used in test examples with the peter corke's puma560 (p560.dyn()) but some values did not match and  i could not figure it out.

Also is there a possibility to generate symbolic representation of forward dynamics of any robot (with torque and dynamic parameters as input) using this software ?

**Comment by cdsousa** [comment]
**R1**: By default is "Khalil" `Lxx Lxy Lxz Lyy Lyz Lzz lx ly lz m` and it is represented around the DH reference frame: i.e., elements of inertia tensor around DH reference frame, first moment of inertia (`m*r`) and mass.
It can also work with "Siciliano" order: https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/robotdef.py#L291

**R2**: This was designed for serial robots only. It is used to produce  customized and optimized symbolic expressions and code for a given robot, i.e. for ficed dof and fixed DH parameters. But if you mean code that will work for all robots, with symbolic DH, then it doesn't make sense to have it in symbolic form as it will be intractable. Better use the generic recursive code in that case.
