### ISSUE TITLE
got an error of "NameError: global name 'math' is not defined" by the example in site

### ISSUE THREAD

**Issue by hao3han3** [cdsousa/SymPyBotics#16]
Hi, I try to create the robot base paramters with the code in the readme.md. 
```
 rbtdef = sympybotics.RobotDef('Example Robot', # robot name
                              [('-pi/2', 0, 0, 'q+pi/2'),  # list of tuples with Denavit-Hartenberg parameters
                                ( 'pi/2', 0, 0, 'q-pi/2')], # (alpha, a, d, theta)
                              dh_convention='standard' # either 'standard' or 'modified')
rbtdef.gravityacc = sympy.Matrix([0.0, 0.0, -9.81]) # optional, this is the default value
rbt = sympybotics.RobotDynCode(rbtdef, verbose=True)
rbt.calc_base_parms()
```
and I got this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win-amd64\egg\sympybotics\robotmodel.py", line 122, in calc_base_parms
  File "build\bdist.win-amd64\egg\sympybotics\dynamics\dynamics.py", line 55, in calc_base_parms
  File "build\bdist.win-amd64\egg\sympybotics\dynamics\dyn_parm_dep.py", line 22, in find_dyn_parm_deps
  File "<string>", line 6, in regressor_func
NameError: global name 'math' is not defined
```
I try to fix it to add "import math", but I can not fide where I can add.
so how to do?
I am running in Python 2.7.15 with the last verstion of Sympy and Numpy libraries (installed by pip).
Thank you

**Comment by phuicy** [comment]
https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/dynamics/dyn_parm_dep.py#L22

So this is the line. I can't see any mention of math, hmmm?

**Comment by hao3han3** [comment]
yes, that is the reason I am so confused.

**Comment by phuicy** [comment]
I would guess this is a python 3 library as i see uses of `print()`.

**Comment by hao3han3** [comment]
could be the problme of x64 version? 
Now I am downloading the python 3 and try it.

**Comment by phuicy** [comment]
I doubt it would have anything with machine architecture. Well i hope it doesn't *shudders*

**Comment by hao3han3** [comment]
same error under python 3.7

Traceback (most recent call last):
```
  File "<stdin>", line 1, in <module>
  File "C:\Python\3\lib\site-packages\sympybotics-1.0.dev0-py3.7.egg\sympybotics\robotmodel.py", line 122, in calc_base_parms
  File "C:\Python\3\lib\site-packages\sympybotics-1.0.dev0-py3.7.egg\sympybotics\dynamics\dynamics.py", line 55, in calc_base_parms
  File "C:\Python\3\lib\site-packages\sympybotics-1.0.dev0-py3.7.egg\sympybotics\dynamics\dyn_parm_dep.py", line 22, in find_dyn_parm_deps
  File "<string>", line 6, in regressor_func
NameError: name 'math' is not defined
```

===================================
this is the code
```
# -*- coding: utf-8 -*-
import math
import sympy
import sympybotics

# import the MDH
rbtdef = sympybotics.RobotDef('exp',  # robot name
                              [(0, 0, 0.32, 'q'),
                               ('pi/2', 0.05, 0, 'q+pi/2'),
                               (0, 0.27, 0, 'q'),
                               ('pi/2', 0.07, 0.3, 'q+pi'),
                               ('pi/2', 0, 0, 'q+pi'),
                               ('pi/2', 0, 0.0785, 'q')],
                              dh_convention='modified'
                              );

# G
rbtdef.gravityacc = sympy.Matrix([0.0, 0.0, -9.81]);

print(rbtdef.dynparms());

rbt = sympybotics.RobotDynCode(rbtdef, verbose=True);

tau_str = sympybotics.robotcodegen.robot_code_to_func('C', rbt.invdyn_code, 'tau_out', 'tau', rbtdef);
print(tau_str)

# matrix H
Mregress = sympybotics.robotcodegen.robot_code_to_func('C', rbt.H_code, 'Mregress', 'Mregress', rbtdef);
print(Mregress)

# base para
rbt.calc_base_parms();
print(rbt.dyn.baseparms)
```

the process to install python is (for both python 2 and 3)
1, download and install the python x64 version
2, use the `python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose` to install numpy and sympy
3, download the sympybotics-master.zip and then `python setup.py install`
that is it.

**Comment by phuicy** [comment]
https://github.com/cdsousa/SymPyBotics/blob/49ac817d5e8bfd1eabc4c56edea325a09b111b55/sympybotics/dynamics/dyn_parm_dep.py#L21

hmmm so it seems to think `regressor_func` is a string. implying :

```python
        Z[i * dof: i * dof + dof, :] = numpy.matrix(
            regressor_func(q, dq, ddq)).reshape(dof, parm_num)
```

should be:
``` python
        Z[i * dof: i * dof + dof, :] = numpy.matrix( regressor_func(q, dq, ddq)).reshape(dof, parm_num)
```
(no line break.)

 I will try and reproduce your bug in a little while.

**Comment by hao3han3** [comment]
I do not think so.
and I got same error after I modified the dyn_parm_dep.py in egg file.

**Comment by hao3han3** [comment]
OK
problem solved
check this:
[https://github.com/crush0441/SymPyBotics/commit/27ba3b2926c6899b2e05a19d76d5837fff0bed2a]

I suggest to fix it

**Comment by hustfzt2** [comment]
> yes, that is the reason I am so confused.
> and also I can not find the "regressor_func" in any files.

Hi, have you solved the "regressor_func"  issue?

**Comment by cdsousa** [comment]
Please open PR whenever it fits.

**Comment by ohmyjesus** [comment]
> OK
> problem solved
> check this:
> [https://github.com/crush0441/SymPyBotics](url)
> 
> ![picpick_2019-01-11_16-55-13](https://user-images.githubusercontent.com/46490355/51044607-c9cc6d80-15c1-11e9-8418-5669f3b896a5.png)
> ![picpick_2019-01-11_16-56-23](https://user-images.githubusercontent.com/46490355/51044659-e4064b80-15c1-11e9-9f09-3b2ee76b64ee.png)
> I found it in Insights - Network
> 
> I suggest to fix it



> OK
> problem solved
> check this:
> [https://github.com/crush0441/SymPyBotics](url)
> 
> ![picpick_2019-01-11_16-55-13](https://user-images.githubusercontent.com/46490355/51044607-c9cc6d80-15c1-11e9-8418-5669f3b896a5.png)
> ![picpick_2019-01-11_16-56-23](https://user-images.githubusercontent.com/46490355/51044659-e4064b80-15c1-11e9-9f09-3b2ee76b64ee.png)
> I found it in Insights - Network
> 
> I suggest to fix it

yes,I solve it, thanks
