### ISSUE TITLE
is it possible to generate Center Of Mass Jacobian for a humanoid robot using SymPyBotics?

### ISSUE THREAD

**Issue by zisang** [cdsousa/SymPyBotics#17]
Hi! I met with some problems with the Center Of Mass Jacobian for a humanoid robot. 

Since humanoid robot has a "floating base" as the root of the kinematics tree, I have no idea how to define a floating base using SymPyBotics, and how to generate Center Of Mass Jacobian code for a robot with a floating base.

It is easy to use RBDyn library to calculate the CoM Jacobian, but it uses more than 1.5 milliseconds, and I want it to be faster, so I want to speed up the calculation by generating the CoM Jacobian code. 

can you guys offer some help? Thanks a lot !

**Comment by cdsousa** [comment]
Hi! SymPyBotics is not prepared to do floating base computations, and I had shifted my area of working so I don't see I can pick developing it any time in the short or medium term. I will let this open so maybe someone else can answer you.

**Comment by zisang** [comment]
Thank you for your answer.
I find it possible to get the CoM Jacobian code using the method _Roy Featherstone_ published.
And I also find that the RBDyn compute the CoM Jacobian faster enough with its release version(about 10us).

**Comment by cdsousa** [comment]
Great that you have found a solution.
