### ISSUE TITLE
how to return a regression matrix

### ISSUE THREAD

**Issue by dwadelinjianxiong** [cdsousa/SymPyBotics#18]
hi,
    I got the base parameters from your example, but have no idea how to get the regression matrix since it's important for identification. Do you have an exmaple about returning the regression matrix, that would help a lot, thanks.

**Comment by cdsousa** [comment]
See the example in the tests:
Line https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L78 generates the whole dynamic symbolic equations;
Line https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L123 generates the source code for the function (denoted by `H_puma560`) which computes the regressor (denoted by `H`);
Line  https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L132 defines the function in Python (denoted by `H_puma560`);
Lines https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L156-L157 call the regressor function for the given numeric inputs.

**Comment by dwadelinjianxiong** [comment]
thank you so much!
