### ISSUE TITLE
Barycentric Parameters

### ISSUE THREAD

**Issue by dwadelinjianxiong** [cdsousa/SymPyBotics#19]
hello,
I would like to know that the barycentric parameters you gave is based on the frame attached to joint or to the mass center of the link.
thanks!

**Comment by cdsousa** [comment]
Attached to joint reference frames (the ones given by the Denavit-Hartenberg formulation).

**Comment by dwadelinjianxiong** [comment]
thank you so much for replying, but I still get stuck in some details about your forward and backard recursive algorithm, would you mind showing me some papers about your works, or recommending some papers about the recursive algorithm you used.

**Comment by dwadelinjianxiong** [comment]
In your code, M[i] = rbtdef.L[i] * dw[i] + w[i].cross( rbtdef.L[i] * w[i]).reshape(3, 1) Matrix(rbtdef.l[i]).cross(dV[i]).reshape(3, 1) confused me so much. To the best of my knowledge, I think it's derive from the Euler-Equation, and use Parallel Axis Theorem to transform the inertia tensor from mass centor attached frames to joint reference frames. However, I still can't get the same recursive equation as yours. Could you please give some advice about that, thank you so much.

**Comment by cdsousa** [comment]
Can you point me the file/line of that?

**Comment by dwadelinjianxiong** [comment]
I am new in github, and I don't know how to point the exact path to you, but the code is from file '\sympybotics\dynamics' and line 87.

**Comment by cdsousa** [comment]
So, this line https://github.com/cdsousa/SymPyBotics/blob/49ac817d5e8bfd1eabc4c56edea325a09b111b55/sympybotics/dynamics/rne_khalil.py#L87 (in Github, you can click the line number to get a link to it).

This is part of the RNE algorithm as formulated by Khalil et al. [1] that is used when the robot geometry has been described by the so-called _**modified** Denavit-Hartenberg formulation_.
When one describes the geometry using the _**standard** Denavit-Hartenberg formulation_, the used RNE algorithm is the one formulated by Park et al. [2].

[1] Khalil, Wisama, and Etienne Dombre. 2002. Modeling, identification & control of robots. London: Hermes Penton.

[2] Park, F. C., J. E. Bobrow, and S. R. Ploen. 1995. “A Lie Group Formulation of Robot Dynamics”. Int. J. Robotics Research 14, no. 6 (): 609–618. doi:10.1177/027836499501400606.

**Comment by dwadelinjianxiong** [comment]
@cdsousa thank you very much, that really help me a lot.
