### ISSUE TITLE
tau_str = sympybotics.robotcodegen.robot_code_to_func('C', rbt.invdyn_code, 'tau_out', 'tau', rbtdef) print(tau_str)

### ISSUE THREAD

**Issue by shaoxingmao** [cdsousa/SymPyBotics#21]
Is this line of code used to generate torque expression？
What is the mean of the expression of "parms[]"?
Thank you very much.

 double x0 = sin(q[1]);
  double x1 = cos(q[1]);
  double x2 = dq[0]*x1;
  double x3 = ddq[0]*x0 + dq[1]*x2;
  double x4 = ddq[0]*x1;
  double x5 = dq[0]*x0;
  double x6 = -dq[1];
  double x7 = x4 + x5*x6;
  double x8 = -0.31*((x0)*(x0)) - 0.31*((x1)*(x1));
  double x9 = 0.31*dq[1];
  double x10 = x4*x8 + x5*x9;
  double x11 = x2*x8;
  double x12 = -parms[16];
  double x13 = parms[17]*x5 + parms[19]*x11 + x12*x2;
  double x14 = cos(q[2]);
  .......
tau_out[0] = ddq[0]*parms[3] + x0*(ddq[1]*parms[12] + parms[10]*x3 + parms[11]*x7 + parms[17]*x10 + x13*x9 + x14*x44 + x15*x38 + x2*x39 + x32*x46 + x37*x47 + x45*x6) + x1*x8*(parms[17]*x3 + parms[19]*x10 + parms[26]*x22 + parms[29]*x10 + x12*x7 + x17*x36 + x19*x28 + x2*x52 + x42*x51 + x47*x5) + x1*(ddq[1]*parms[14] + dq[1]*x48 + parms[11]*x3 + parms[13]*x7 + parms[18]*x31 + x10*x12 + x11*x49 + x15*x44 + x16*x38 + x39*x50);
  tau_out[1] = ddq[1]*parms[15] + 0.31*ddq[1]*parms[16] + 0.31*dq[1]*x49 + parms[12]*x3 + parms[14]*x7 + parms[16]*x32 - parms[17]*x31 + 0.31*parms[19]*x32 + 0.31*x13*x50 + 0.31*x15*(parms[28]*x20 + parms[29]*x33 + x22*x30 + x23*x42 + x29*x43) + 0.31*x16*(parms[27]*x19 + parms[29]*x40 + x20*x26 + x21*x29 + x34*x36) - x2*x48 + 0.31*x3*x46 + x45*x5 + x52*x9 + x53;
  tau_out[2] = x53;

**Comment by cdsousa** [comment]
> Is this line of code used to generate torque expression？

Yes, it is.

The `params` variable is the vector (C array) of the numeric values of the dynamic parameters in the order given by `rbt.dyn.dynparms` (which is 'Khalil' order by default).
