### ISSUE TITLE
How to Obtain Observation Matrix？

### ISSUE THREAD

**Issue by yyloveyueyue** [cdsousa/SymPyBotics#24]
when i get the Dynamic base parameters by code of 'rbt.calc_base_parms() rbt.dyn.baseparms'
how can i know the Observation Matrix at this point,and transformation matrix from parameters to Dynamic base parameters.
Thank you

**Comment by cdsousa** [comment]
The observation full matrix (aka  regressor full matrix `H`), can be obtained as in this example https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L123

The transformation matrix from parameters to base parameters, let's call it `K` can be obtained  by `K = rbt.dyn.Pb.T + rbt.dyn.Kd * rbt.dyn.Pd.T` as I did in the block [221] of http://htmlpreview.github.io/?https://github.com/cdsousa/wam7_dyn_ident/blob/master/WAM7+Dynamic+Parameter+Identification.html

To better know the notation check https://www.researchgate.net/publication/262483999_Physical_feasibility_of_robot_base_inertial_parameter_identification_A_linear_matrix_inequality_approach
