### ISSUE TITLE
How are these matrices T_pcorke, J_pcorke, tau_pcorke obtained?

### ISSUE THREAD

**Issue by Alger2018** [cdsousa/SymPyBotics#27]
The matrices like T_pcorke, J_pcorke, tau_pcorke in test_results.py.How are these matrices obtained to verify the proposed method.

**Comment by cdsousa** [comment]
Sorry, I don't remember for sure -_- , it was 7 years ago, by I would say that that come from Peter Corke's Robotics Toolbox in either Matlab (https://petercorke.com/toolboxes/robotics-toolbox/) or Python (https://petercorke.com/toolboxes/octave-python-and-julia/)

**Comment by Alger2018** [comment]
Thank you very much!
