### ISSUE TITLE
Negative Torque

### ISSUE THREAD

**Issue by Alger2018** [cdsousa/SymPyBotics#28]
tau = [0.986185688,16.1055551,-6.54839495,0.00626452648,-0.0208972707,0.0000559805924] in  https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py#L140.
Why some torque is negative since the accelerations ddq_test = [0.707405815485141, 0.25295715193420953, 0.9763909835998361, 0.8412822676113918, 0.4867768296473465, 0.11480270540937143] are positive?

**Comment by cdsousa** [comment]
Because tau is the sum of several components, in that case: inertial (where acceleration enters), Coriolis and gravity. In this case, since all joint accelerations are positive, the inertial term will be positive, but the others can be negative.
