### ISSUE TITLE
Excitation trajectory

### ISSUE THREAD

**Issue by Zhaotianzheng** [cdsousa/SymPyBotics#36]
Great work!
I want to optimize the excitation trajectory, but I don't know how to get the W (linear independent regression matrix). And if I get the W, should I optimize all W(t) （cause the trajectory has about 10 seconds）or just find the W(t0) with the max cond number and optimize that or make a super big matrix W include all the data and optmize....
Thank you so much for this project. Hope I can get your  advice. Thank you!

**Comment by cdsousa** [comment]
If I recall correctly, make a super big matrix W include all the data and optimize, check Swevers 1997 on that.

However, note: optiminzing W can be made smaller if you use less datapoints. You can generate datapoints with lower frequency that the frequency that is needed to control the real robot trajectory.
