### ISSUE TITLE
Is it possible to generate forward dynamics code?

### ISSUE THREAD

**Issue by jnh277** [cdsousa/SymPyBotics#38]
Hi,

I was wondering if there is a way to generate code for the forward dynamics rather than the inverse dynamics. I want to generate a function to return ddq given tau, q, dq, and the params. I have found an example of how to compute the forward kinematics and was wondering if there was a similar option?

Thanks in advance

**Comment by jnh277** [comment]
After digging into the existing code I realised the it is possible to generate code for the corriolis term, mass matrix and gravitational term. The components needed for the forward dynamics. This is not obvious from the readme but does exist

Using
print(rbt._codes)

shows what can be generated

**Comment by cdsousa** [comment]
Yeah, the right way is to compute the standalone terms and then compute the acceleration using the forward dynamics equation (https://robotacademy.net.au/lesson/forward-dynamics/,  or https://estudogeral.sib.uc.pt/bitstream/10316/27082/1/Robot%20manipulators.pdf eq 5.1).
See some usage of this package here https://github.com/cdsousa/SymPyBotics/blob/master/sympybotics/tests/test_results.py
