### ISSUE TITLE
Is this toolbox suitable for robots with prismatic joints?

### ISSUE THREAD

**Issue by Yonson39** [cdsousa/SymPyBotics#39]
hi，Is this toolbox suitable for robots with prismatic joints?
such as  a robot with a revolute joint and a prismatic joint.
Looking forward to your reply!

**Comment by cdsousa** [comment]
> hi，Is this toolbox suitable for robots with prismatic joints? such as a robot with a revolute joint and a prismatic joint. Looking forward to your reply!

https://github.com/cdsousa/SymPyBotics/issues/12
