### ISSUE TITLE
Is it possible to construct the dynamics of robot with compliance actuator?

### ISSUE THREAD

**Issue by ycHepth** [cdsousa/SymPyBotics#42]
The examples and code given focus on the modeling of rigid joint robots, but for robots with flexibility, such as series elastic actuators, it does not seem possible to calculate the regression matrix directly with this tool. I noticed that when defining the robot, the simplified motor dynamics model could be introduced into the total model, which would introduce a new inertia parameter {I_a} about the linkage variable {q} rather than the motor variable {theta}. Therefore, is it possible to modify some place to adapt to compliance actuator?

**Comment by cdsousa** [comment]
The code is not prepared/tested for that, but with some medium effort it may be possible. I stopped working with, even knowing, this code long ago though.
